context:
  version: "2.22.0"

package:
  name: lumen-diff
  version: ${{ version }}

source:
  url: https://github.com/jnsahaj/lumen/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2ff20a19517efb302af25cf6b36cf82fea72dc48a38ba3bdbb868a390916928c

build:
  number: 0
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - make

tests:
  - script: lumen --help
  - package_contents:
      bin:
        - lumen
      strict: true

about:
  homepage: https://github.com/jnsahaj/lumen
  summary: Beautiful git diff viewer, generate commits with AI, get summary of changes, all from the CLI
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://docs.rs/lumen
  repository: https://github.com/jnsahaj/lumen

extra:
  recipe-maintainers:
    - pavelzw
